[package]
name = "fluminurs"
version = "0.1.0"
authors = ["Julius Putra Tanu Setiaji <indocomsoft@gmail.com>"]
edition = "2018"

[dependencies]
ammonia = "2.0.0"
cookie = "0.11.0"
htmlescape = "0.3.1"
rand = "0.6.5"
reqwest = "0.9.9"
rpassword = "2.1.0"
select = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.0"
serde_urlencoded = "0.5.4"
url = "1.7.2"
